name: flutter_first_draft
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  audioplayers: ^5.2.1
  just_audio: ^0.9.12
  assets_audio_player: ^3.0.8
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/AudioFiles/stairs.wav

